name: Deploy Website Otomatis

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # Paksa pake Node 24 biar gak warning
    steps:
      - name: Ambil kode dari repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install & Build
        run: |
          npm install
          npm run build

      - name: Kirim ke cPanel (SFTP)
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          port: 45022
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_path: './dist/*'
          remote_path: '/public_html/node-app/dist/'
          sftp_only: true
